PROGRAM WRITE_TECPLOT
USE MOD_PART0
USE MOD_PART1
USE MOD_RECLA
USE MOD_PRO
USE MOD_TRAJ
USE MOD_LINES

IMPLICIT NONE
INTEGER  VAL,ISTAT
INTEGER  II,JJ,KK,LENVAR
INTEGER  NUMFILE 
REAL     X0,X1,Y0,Y1                 ! FIGURE DOMAIN
REAL     NORTHX,NORTHY
INTEGER  NORTHS,PARTICALSIZE        ! NORTH POSITION
CHARACTER(LEN=100)                  :: PARANAME,FILEPATH            ! PRE READ PATH
CHARACTER(LEN=200)                  :: OUTPATH,OUTNAME,PRENAME      ! POST OUTPUT PATH AND NAME
CHARACTER(LEN=100)                  :: TMPVAL,FLAG
CHARACTER(LEN=100),ALLOCATABLE     :: DATNAME(:),FILENAME(:)       ! DATNAME: TECPLOT RES ; FILENAME : OUTPUT PREFIX
CHARACTER(LEN=100)                  :: RECLAREA,PROAREA             ! RECLA AND PROTECT ZONE
LOGICAL                             :: RECLA,PRO,TRAJ,LINE        ! LOGICAL OF RECLA , PROTECT ZONE AND TRAJ
! RECLA VARIABLE
INTEGER                             :: NUMRECLA
CHARACTER(LEN=100),ALLOCATABLE     :: RECLANAME(:)   ! XYZ
! PROTECT ZONE VARIABLE
INTEGER                             :: NUMPRO
CHARACTER(LEN=100),ALLOCATABLE     :: PROTECTNAME(:) ! XYZ
! TRAJ PREFIX
CHARACTER(LEN=100)                  :: TRAJNAME,TRAJPREFIX       ! XYZ,PREFIX
INTEGER                             :: NUMTIME
REAL,ALLOCATABLE                   :: TIME0(:)
! LINE VARIABLE
INTEGER                             :: NUMLINE
CHARACTER(LEN=100),ALLOCATABLE     :: LINENAME(:),LINECOLOR(:)
REAL,ALLOCATABLE                   :: LINEWIDTH(:) ! XYZ
! Oil spill location
REAL                                :: XX0,YY0

WRITE(*,'(A)',ADVANCE='NO') 'Input control File (*.dat; ?[.dat]):'
READ(*,'(A)') PARANAME
! READ PARA INFO
OPEN(UNIT=8,FILE=PARANAME,STATUS='OLD')
READ(8,*)
READ(8,100) FILEPATH
READ(8,*) 
READ(8,300) NUMFILE
ALLOCATE(DATNAME(NUMFILE))
ALLOCATE(FILENAME(NUMFILE))
READ(8,*) 
DO II=1,NUMFILE
    READ(8,100) DATNAME(II)
ENDDO
READ(8,*)  
READ(8,200) X0
READ(8,200) Y0
READ(8,200) X1
READ(8,200) Y1
READ(8,*)  
READ(8,200) NORTHX
READ(8,200) NORTHY
READ(8,"(I10)") NORTHS
READ(8,*)  
READ(8,*)   XX0
READ(8,*)   YY0
READ(8,*)
READ(8,*)
READ(8,*) RECLA,PRO,LINE
READ(8,*) 
READ(8,*) NUMRECLA
ALLOCATE(RECLANAME(NUMRECLA))
DO II=1,NUMRECLA
    READ(8,100) RECLANAME(II)
ENDDO
READ(8,*) 
READ(8,*) NUMPRO
ALLOCATE(PROTECTNAME(NUMPRO))
DO II=1,NUMPRO
    READ(8,100) PROTECTNAME(II)
ENDDO
READ(8,*)
READ(8,*) NUMLINE
ALLOCATE(LINENAME(NUMLINE))
ALLOCATE(LINECOLOR(NUMLINE))
ALLOCATE(LINEWIDTH(NUMLINE))
DO II=1,NUMLINE
    READ(8,100) LINENAME(II)
ENDDO
READ(8,*) (LINECOLOR(II),II=1,NUMLINE)
READ(8,*) (LINEWIDTH(II),II=1,NUMLINE)
READ(8,*)
READ(8,*) OUTPATH
READ(8,*) PRENAME
DO II=1,NUMFILE
    READ(8,100) FILENAME(II)
ENDDO
READ(8,*)
READ(8,*) TRAJ
READ(8,*)
READ(8,*) NUMTIME
ALLOCATE(TIME0(NUMTIME))
READ(8,*) (TIME0(II),II=1,NUMTIME)
READ(8,*)
READ(8,*) TRAJNAME
READ(8,*)
READ(8,*)
READ(8,*) TRAJPREFIX
CLOSE(8)
! END PARA INFO
PARTICALSIZE=NORTHS
DO II=1,NUMFILE
    LENVAR=LEN_TRIM(DATNAME(II))
    TMPVAL=TRIM(FILENAME(II))
    DO JJ=1,LENVAR
        FLAG=TMPVAL(JJ:JJ)
        IF(FLAG.EQ.'.') THEN
            KK=JJ
        ENDIF
    ENDDO
    OUTNAME=TRIM(OUTPATH)//TRIM(PRENAME)//TRIM(TMPVAL(1:KK-1))//".MCR"
    print*,TRIM(OUTPATH)//TRIM(PRENAME)//TRIM(TMPVAL(1:KK-1))//".MCR"
    stop
    OPEN(UNIT=10,FILE=TRIM(TRIM(OUTPATH)//TRIM(PRENAME)//TRIM(TMPVAL(1:KK-1))//".MCR"), &
    &                 STATUS='unknown',ENCODING='utf-8')
    ! PART0
    WRITE(10,100)"#!MC 1200"
    WRITE(10,100)"# Created by Tecplot 360 build 12.2.0.9077"
    WRITE(10,100)"#$!VarSet |MFBD| = 'C:\Users\John\Documents'"
    WRITE(10,100)"## 定出一个图的左下角与右上角坐标"
    ! PART1
    WRITE(10,400) "$!VarSet |XZX| = ",X0
    WRITE(10,400) "$!VarSet |YZX| = ",Y0
    WRITE(10,400) "$!VarSet |XYS| = ",X1
    WRITE(10,400) "$!VarSet |YYS| = ",Y1
    ! PART2
    WRITE(10,100) "## 指北针的位置坐标"
    WRITE(10,100) "$!VARSET |X_GEO|=6"
    WRITE(10,100) "$!VARSET |Y_GEO|=90"
    WRITE(10,100) "$!VARSET |X_TXT| = (|X_GEO|-0.78)"
    WRITE(10,100) "$!VARSET |Y_TXT| = (|Y_GEO|+1)"
    WRITE(10,100) "## 比例尺的坐标与尺度"
    ! PART3
    WRITE(10,400) "$!VARSET |X_BLC|=  ",NORTHX
    WRITE(10,400) "$!VARSET |Y_BLC|=  ",NORTHY
    WRITE(10,"(A,I10)") "$!VARSET |LEN_BLC|=",NORTHS
    ! PART4
    WRITE(10,100)"$!VARSET |HIGH_BLC|=(|LEN_BLC|/10)"
    WRITE(10,100)"$!VARSET |LEN_BLC2|=(|LEN_BLC|/2)"
    WRITE(10,100)"$!VARSET |X_BLC2|=(|X_BLC|+|LEN_BLC2|)"
    WRITE(10,100)"$!VARSET |TXT_BLC_X|=(|X_BLC2|-|LEN_BLC2|/2)"
    WRITE(10,100)"$!VARSET |TXT_BLC_Y|=(|Y_BLC|+|HIGH_BLC|*2)"
    WRITE(10,100)""
    WRITE(10,100)""
    ! PART5
    WRITE(10,100)  "$!READDATASET  '"//'"'//TRIM(FILEPATH)//TRIM(DATNAME(II))//'"'//"'"
    CLOSE(10)
    ! PART6
    stop
    !OUTNAME=TRIM(OUTPATH)//TRIM(PRENAME)//TRIM(TMPVAL(1:KK-1))//".MCR"
    CALL  WRITE_PART0(OUTNAME)
    ! OIL SPILL LOCATION
    OPEN(UNIT=10,FILE=TRIM(TRIM(OUTPATH)//TRIM(PRENAME)//TRIM(TMPVAL(1:KK-1))//".MCR"),  &
    &                 STATUS='OLD',ENCODING='utf-8',ACCESS='APPEND')
    WRITE(10,100) "#画溢油点"
    WRITE(10,100) "$!ATTACHGEOM "
    WRITE(10,100) "     GEOMTYPE = CIRCLE "
    WRITE(10,100) "ANCHORPOS "
    WRITE(10,100) "    {"
    WRITE(10,400) "X =",XX0
    WRITE(10,400) "Y =",YY0
    WRITE(10,100) "    }"
    !WRITE(10,100) " NUMELLIPSEPTS = 4 "
    WRITE(10,100) "  COLOR = BLUE"
    WRITE(10,100) "  ISFILLED = YES"
    WRITE(10,100) " FILLCOLOR = BLACK"
    WRITE(10,100) " RAWDATA "
    WRITE(10,200) NORTHS*1./22
    CLOSE(10)
    !围垦和保护区  线

    PRINT*,OUTNAME
    IF(RECLA) THEN
        CALL WRITE_RECLA(OUTNAME,NUMRECLA,RECLANAME)
    ENDIF
    IF(PRO) THEN
        CALL WRITE_PRO(OUTNAME,NUMPRO,PROTECTNAME)
    ENDIF
    IF(LINE) THEN
        CALL WRITE_LINES(OUTNAME,NUMLINE,LINENAME,LINECOLOR,LINEWIDTH)
    ENDIF
    ! 等值线图
    CALL WRITE_PART1(OUTNAME)
    OPEN(UNIT=10,FILE=TRIM(OUTNAME),STATUS='OLD',ENCODING='utf-8',ACCESS='APPEND')
    WRITE(10,100)"$!EXPORTSETUP EXPORTFNAME = '"//TRIM(OUTPATH)//TRIM(PRENAME)//'_'//TRIM(FILENAME(II))//"'"
    WRITE(10,100)"$!EXPORT"
    WRITE(10,100)"  EXPORTREGION = CURRENTFRAME"
    CLOSE(10)
ENDDO    
    IF (TRAJ) THEN
         OUTNAME=TRIM(OUTPATH)//TRIM(PRENAME)//'Partical'//".MCR"
         OPEN(UNIT=20,FILE=TRIM(OUTNAME),STATUS='REPLACE',ENCODING='utf-8',ACCESS='APPEND')
        ! PART0
        WRITE(20,100)"#!MC 1200"
        WRITE(20,100)"# Created by Tecplot 360 build 12.2.0.9077"
        WRITE(20,100)"#$!VarSet |MFBD| = 'C:\Users\John\Documents'"
        WRITE(20,100)"## 定出一个图的左下角与右上角坐标"
        ! PART
        WRITE(20,400) "$!VarSet |XZX| = ",X0
        WRITE(20,400) "$!VarSet |YZX| = ",Y0
        WRITE(20,400) "$!VarSet |XYS| = ",X1
        WRITE(20,400) "$!VarSet |YYS| = ",Y1
        ! PART2
        WRITE(20,100) "## 指北针的位置坐标"
        WRITE(20,100) "$!VARSET |X_GEO|=6"
        WRITE(20,100) "$!VARSET |Y_GEO|=90"
        WRITE(20,100) "$!VARSET |X_TXT| = (|X_GEO|-0.78)"
        WRITE(20,100) "$!VARSET |Y_TXT| = (|Y_GEO|+1)"
        WRITE(20,100) "## 比例尺的坐标与尺度"
        ! PART3
        WRITE(20,400) "$!VARSET |X_BLC|=  ",NORTHX
        WRITE(20,400) "$!VARSET |Y_BLC|=  ",NORTHY
        WRITE(20,"(a,I10)") "$!VARSET |LEN_BLC|=",NORTHS
        ! PART4
        WRITE(20,100)"$!VARSET |HIGH_BLC|=(|LEN_BLC|/10)"
        WRITE(20,100)"$!VARSET |LEN_BLC2|=(|LEN_BLC|/2)"
        WRITE(20,100)"$!VARSET |X_BLC2|=(|X_BLC|+|LEN_BLC2|)"
        WRITE(20,100)"$!VARSET |TXT_BLC_X|=(|X_BLC2|-|LEN_BLC2|/2)"
        WRITE(20,100)"$!VARSET |TXT_BLC_Y|=(|Y_BLC|+|HIGH_BLC|*2)"
        WRITE(20,100)""
        WRITE(20,100)""
        ! PART5
        WRITE(20,100)  "$!READDATASET  '"//'"'//TRIM(FILEPATH)//TRIM(DATNAME(1))//'"'//"'"
        CLOSE(20)
        ! PART6
        CALL  WRITE_PART0(OUTNAME)
        ! 溢油点

        !围垦和保护区
        IF(RECLA) THEN
            CALL WRITE_RECLA(OUTNAME,NUMRECLA,RECLANAME)
        ENDIF
        IF(PRO) THEN
            CALL WRITE_PRO(OUTNAME,NUMPRO,PROTECTNAME)
        ENDIF  
        CALL  WRITE_TRAJ(OUTNAME,TRAJNAME,TIME0,PARTICALSIZE)
        OPEN(UNIT=20,FILE=TRIM(OUTNAME),STATUS='OLD',ENCODING='utf-8',ACCESS='APPEND')
         ! PART7
        WRITE(20,100)"$!EXPORTSETUP EXPORTFNAME = '"//TRIM(OUTPATH)//TRIM(PRENAME)//'_'//TRIM(TRAJPREFIX)//"'"
        WRITE(20,100)"$!EXPORT"
        WRITE(20,100)"  EXPORTREGION = CURRENTFRAME"
        CLOSE(20)
    ENDIF
    100 FORMAT (A)
    200 FORMAT (F20.5)
    300 FORMAT (I2)
    400 FORMAT (A,F20.5)
END PROGRAM WRITE_TECPLOT
    
